### ISSUE TITLE
Block Deleting Comments (web-author-block-deleting-suggestions plugin)

### ISSUE THREAD

**Issue by reifsnid** [oxygenxml/web-author-sample-plugins#5]
Hi,

I'm looking into installing the [web-author-block-deleting-suggestions](https://github.com/oxygenxml/web-author-sample-plugins/tree/master/web-author-block-deleting-suggestions) plugin, but I'm also wondering if it would be possible to block deleting comments as well?

I've looked through the ReviewController SDK documentation (https://www.oxygenxml.com/InstData/Editor/SDK/javadoc/ro/sync/ecss/extensions/api/webapp/review/ReviewController.html) but it doesn't look like there's a method that gets comments like there is for getting changes (getChangeHighlights).

Do you have any recommendations for how to also block deleting comments?

Thank you!

Daniel

**Comment by mihaela-calotescu** [comment]
Hello, 

We just added a sample plugin that blocks deleting other users review comments: [web-author-block-deleting-comments](https://github.com/oxygenxml/web-author-sample-plugins/tree/master/web-author-block-deleting-comments)

Best Regards, 
Mihaela.
